steps:
# 1. Install dependencies for the build job
- name: 'gcr.io/cloud-builders/pip'
  args: ['install', '-r', 'requirements.txt']

# 2. Run the wiki loader
- name: 'python:3.11'
  entrypoint: 'python'
  args: ['wiki_loader.py']
  id: 'load-wiki-data'

# 3. Run the data cleaner
- name: 'python:3.11'
  entrypoint: 'python'
  args: ['clean_data.py']
  id: 'clean-data'
  waitFor: ['load-wiki-data']

# 4. Run the index builder
# This step needs the OLLAMA_HOST var and VPC access
- name: 'python:3.11'
  entrypoint: 'python'
  args: ['build_index.py']
  id: 'build-index'
  waitFor: ['clean-data']
  env:
  - 'OLLAMA_HOST=http://10.180.0.2:11434'
  # This 'network' field is crucial. Replace <YOUR_VPC_NAME>
  network: 'projects/${PROJECT_ID}/global/networks/default'

# 5. Compress the built index
- name: 'bash'
  args:
  - '-c'
  - 'tar -czf faiss_index.tar.gz faiss_index'
  id: 'compress-index'
  waitFor: ['build-index']

# 6. Upload the compressed index to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'faiss_index.tar.gz', 'gs://notchnet/faiss_index.tar.gz']
  id: 'upload-index'
  waitFor: ['compress-index']

timeout: '3600s' # 1 hour, increase if index build takes longer